# 1. El motor (driver) para conectar con MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/sistema_bancario
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# Propiedad: JPA crea las tablas

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Muestra el mensaje de error
server.error.include-message=always

# Muestra por qué falló la validación
server.error.include-binding-errors=always

# Muestra qué excepciones ocurrieron
server.error.include-exception=true